# Generated by Django 4.2.4 on 2023-11-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='desc',
        ),
        migrations.AddField(
            model_name='movie',
            name='code',
            field=models.CharField(default='qwerty', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(),
        ),
    ]
